/**
 * Comprehensive English word list for Call My Word
 * Contains common English words suitable for word games (4+ letters)
 */

export const ENGLISH_WORDS = new Set([
  // === A ===
  "able", "about", "above", "abuse", "acid", "acre", "across", "acted", "action",
  "active", "actor", "acute", "adapt", "added", "admit", "adopt", "adult", "advice",
  "advise", "affect", "afford", "afraid", "after", "again", "against", "agent", "agree",
  "ahead", "aimed", "aircraft", "alarm", "album", "alert", "alien", "align", "alike",
  "alive", "allow", "alloy", "alone", "along", "alpha", "alter", "always", "amaze",
  "among", "amount", "ample", "amuse", "angel", "anger", "angle", "angry", "animal",
  "ankle", "annual", "answer", "anyone", "apart", "appeal", "appear", "apple", "apply",
  "apron", "arena", "argue", "arise", "armor", "array", "arrow", "arson", "asset",
  "assist", "assume", "atlas", "atmosphere", "atom", "attach", "attack", "attempt",
  "attend", "attract", "auction", "audio", "audit", "aunt", "author", "autumn", "avenue",
  "average", "avoid", "await", "awake", "award", "aware", "awful",

  // === B ===
  "baby", "back", "bacon", "badge", "badly", "baker", "balance", "ball", "ballot",
  "bamboo", "banana", "band", "bank", "banner", "barrel", "base", "basic", "basin",
  "basis", "basket", "batch", "bath", "battle", "beach", "beam", "bean", "bear",
  "beard", "beast", "beat", "beauty", "became", "become", "bedroom", "beef", "been",
  "beer", "before", "began", "begin", "begun", "behavior", "behind", "being", "belief",
  "believe", "bell", "belly", "belong", "below", "belt", "bench", "bend", "beneath",
  "benefit", "berry", "beside", "besides", "best", "better", "between", "beyond", "bicycle",
  "bigger", "bike", "bill", "billion", "bind", "bird", "birth", "bitter", "black",
  "blade", "blame", "blank", "blanket", "blast", "blaze", "bleed", "blend", "bless",
  "blind", "block", "blood", "bloom", "blown", "blue", "board", "boat", "body",
  "boil", "bold", "bolt", "bomb", "bond", "bone", "bonus", "book", "boom",
  "boost", "boot", "booth", "border", "bore", "born", "borrow", "boss", "both",
  "bother", "bottle", "bottom", "bought", "bounce", "bound", "bowl", "boxer", "brain",
  "brake", "branch", "brand", "brass", "brave", "bread", "break", "breast", "breath",
  "breathe", "breed", "breeze", "brick", "bride", "bridge", "brief", "bright", "brilliant",
  "bring", "broad", "broke", "broken", "bronze", "brook", "brother", "brought", "brown",
  "brush", "bubble", "bucket", "budget", "build", "built", "bulk", "bullet", "bunch",
  "bundle", "burden", "bureau", "burn", "burst", "bury", "bush", "business", "busy",
  "butter", "button", "buyer", "bypass",

  // === C ===
  "cabin", "cabinet", "cable", "cage", "cake", "calcium", "calculate", "calendar", "call",
  "calm", "came", "camera", "camp", "campaign", "campus", "canal", "cancel", "cancer",
  "candidate", "candle", "candy", "capable", "capacity", "capital", "captain", "capture", "carbon",
  "card", "care", "career", "careful", "cargo", "carpet", "carrot", "carry", "cart",
  "cartoon", "carve", "case", "cash", "casino", "cast", "castle", "casual", "catch",
  "category", "cattle", "caught", "cause", "caution", "cave", "cease", "ceiling", "celebrate",
  "cell", "cement", "center", "central", "century", "cereal", "ceremony", "certain", "chain",
  "chair", "chairman", "challenge", "chamber", "champion", "chance", "change", "channel", "chaos",
  "chapter", "character", "charge", "charity", "charm", "chart", "chase", "cheap", "cheat",
  "check", "cheek", "cheer", "cheese", "chef", "chemical", "cherry", "chest", "chicken",
  "chief", "child", "children", "chin", "chip", "chocolate", "choice", "choir", "choose",
  "chop", "chosen", "church", "cigarette", "circle", "circuit", "circumstance", "citizen", "city",
  "civil", "claim", "class", "classic", "classroom", "clause", "clay", "clean", "clear",
  "clerk", "clever", "click", "client", "cliff", "climate", "climb", "clinic", "clock",
  "clone", "close", "closed", "closet", "cloth", "clothes", "cloud", "club", "clue",
  "cluster", "coach", "coal", "coast", "coat", "code", "coffee", "coin", "cold",
  "collapse", "collar", "collect", "college", "colony", "color", "column", "combat", "combine",
  "come", "comedy", "comfort", "comic", "coming", "command", "comment", "commerce", "commercial",
  "commission", "commit", "committee", "common", "communicate", "community", "company", "compare", "comparison",
  "compete", "competition", "competitive", "complain", "complaint", "complete", "complex", "complicated", "component",
  "compose", "composition", "compound", "comprehensive", "computer", "concentrate", "concentration", "concept", "concern",
  "concerned", "concert", "conclude", "conclusion", "concrete", "condition", "conduct", "conference", "confidence",
  "confident", "confirm", "conflict", "confront", "confuse", "confusion", "congress", "connect", "connection",
  "conscience", "conscious", "consensus", "consequence", "conservative", "consider", "consideration", "consist", "consistent",
  "constant", "constitute", "constitution", "construct", "construction", "consult", "consume", "consumer", "contact",
  "contain", "container", "contemporary", "content", "contest", "context", "continue", "contract", "contrast",
  "contribute", "contribution", "control", "controversial", "controversy", "convenient", "convention", "conversation", "convert",
  "convince", "cook", "cookie", "cooking", "cool", "cooperate", "cooperation", "cope", "copy",
  "core", "corn", "corner", "corporate", "corporation", "correct", "corridor", "corrupt", "cost",
  "costume", "cottage", "cotton", "couch", "cough", "could", "council", "count", "counter",
  "country", "county", "couple", "courage", "course", "court", "cousin", "cover", "coverage",
  "crack", "craft", "crash", "crazy", "cream", "create", "creation", "creative", "creature",
  "credit", "creek", "crew", "crime", "criminal", "crisis", "criterion", "critic", "critical",
  "criticism", "criticize", "crop", "cross", "crowd", "crucial", "cruel", "crush", "crystal",
  "cultural", "culture", "curious", "current", "currently", "curriculum", "curtain", "curve", "custom",
  "customer", "cycle",

  // === D ===
  "daddy", "daily", "dairy", "damage", "damp", "dance", "dancer", "danger", "dangerous",
  "dare", "dark", "darkness", "data", "database", "date", "daughter", "dawn", "dead",
  "deadline", "deal", "dealer", "dear", "death", "debate", "debt", "decade", "decent",
  "decide", "decision", "deck", "declare", "decline", "decorate", "decrease", "dedicate", "deed",
  "deep", "deer", "defeat", "defend", "defense", "deficit", "define", "definitely", "definition",
  "degree", "delay", "delegate", "delete", "delicate", "delight", "deliver", "delivery", "demand",
  "democracy", "democratic", "demonstrate", "denial", "dense", "deny", "department", "depend", "dependent",
  "deposit", "depress", "depression", "depth", "deputy", "derive", "describe", "description", "desert",
  "deserve", "design", "designer", "desire", "desk", "desperate", "despite", "destination", "destroy",
  "destruction", "detail", "detailed", "detect", "detective", "determine", "develop", "development", "device",
  "devil", "devote", "dialogue", "diamond", "diary", "dictate", "dictionary", "died", "diet",
  "differ", "difference", "different", "difficult", "difficulty", "digital", "dignity", "dimension", "dine",
  "dinner", "dinosaur", "direct", "direction", "directly", "director", "dirt", "dirty", "disability",
  "disabled", "disagree", "disappear", "disaster", "discipline", "discount", "discover", "discovery", "discuss",
  "discussion", "disease", "dish", "dismiss", "disorder", "display", "dispute", "distance", "distant",
  "distinct", "distinction", "distinguish", "distribute", "distribution", "district", "disturb", "dive", "diverse",
  "diversity", "divide", "division", "divorce", "doctor", "document", "does", "dollar", "domain",
  "domestic", "dominant", "dominate", "donate", "done", "door", "dose", "double", "doubt",
  "down", "downtown", "dozen", "draft", "drag", "dragon", "drain", "drama", "dramatic",
  "draw", "drawer", "drawing", "dream", "dress", "drew", "dried", "drift", "drill",
  "drink", "drive", "driven", "driver", "drop", "drought", "drove", "drown", "drug",
  "drum", "drunk", "dual", "duck", "dude", "dump", "during", "dust", "duty",
  "dwell", "dying", "dynamic",

  // === E ===
  "each", "eager", "eagle", "early", "earn", "earnings", "earth", "ease", "easily",
  "east", "eastern", "easy", "eaten", "echo", "economic", "economics", "economist", "economy",
  "edge", "edition", "editor", "educate", "education", "educational", "educator", "effect", "effective",
  "effectively", "efficiency", "efficient", "effort", "eight", "either", "elaborate", "elder", "elderly",
  "elect", "election", "electric", "electrical", "electricity", "electronic", "electronics", "element", "elementary",
  "elephant", "elevator", "eliminate", "elite", "else", "elsewhere", "email", "embarrass", "embrace",
  "emerge", "emergency", "emission", "emotion", "emotional", "emperor", "emphasis", "emphasize", "empire",
  "employ", "employee", "employer", "employment", "empty", "enable", "encounter", "encourage", "enemy",
  "energy", "enforce", "engage", "engagement", "engine", "engineer", "engineering", "enhance", "enjoy",
  "enormous", "enough", "ensure", "enter", "enterprise", "entertainment", "enthusiasm", "entire", "entirely",
  "entrance", "entry", "envelope", "environment", "environmental", "episode", "equal", "equally", "equation",
  "equipment", "equivalent", "error", "escape", "especially", "essay", "essence", "essential", "essentially",
  "establish", "establishment", "estate", "estimate", "eternal", "ethical", "ethics", "ethnic", "evaluate",
  "evaluation", "even", "evening", "event", "eventually", "ever", "every", "everybody", "everyday",
  "everyone", "everything", "everywhere", "evidence", "evident", "evil", "evolution", "evolve", "exact",
  "exactly", "exam", "examination", "examine", "example", "exceed", "excellent", "except", "exception",
  "exchange", "excite", "excited", "excitement", "exciting", "exclude", "excuse", "execute", "executive",
  "exercise", "exhibit", "exhibition", "exist", "existence", "existing", "exit", "expand", "expansion",
  "expect", "expectation", "expense", "expensive", "experience", "experiment", "experimental", "expert", "expertise",
  "explain", "explanation", "explicit", "explode", "exploit", "explore", "explosion", "export", "expose",
  "exposure", "express", "expression", "extend", "extension", "extensive", "extent", "external", "extra",
  "extraordinary", "extreme", "extremely",

  // === F ===
  "fabric", "face", "facility", "fact", "factor", "factory", "faculty", "fade", "fail",
  "failure", "fair", "fairly", "fairy", "faith", "fake", "fall", "false", "fame",
  "familiar", "family", "famous", "fancy", "fantastic", "fantasy", "fare", "farm", "farmer",
  "fashion", "fast", "faster", "fate", "father", "fault", "favor", "favorite", "fear",
  "feast", "feat", "feather", "feature", "federal", "feed", "feedback", "feel", "feeling",
  "fellow", "felt", "female", "fence", "festival", "fetch", "fever", "fewer", "fiber",
  "fiction", "field", "fierce", "fifteen", "fifth", "fifty", "fight", "fighter", "fighting",
  "figure", "file", "fill", "filled", "film", "filter", "final", "finally", "finance",
  "financial", "find", "finding", "fine", "finger", "finish", "fire", "firm", "first",
  "fish", "fishing", "fitness", "five", "fixed", "flag", "flame", "flash", "flat",
  "flavor", "fled", "flesh", "flexible", "flight", "flip", "float", "flock", "flood",
  "floor", "flour", "flow", "flower", "fluid", "flush", "focus", "fold", "folk",
  "follow", "following", "food", "fool", "foot", "football", "force", "forecast", "foreign",
  "forest", "forever", "forget", "forgive", "fork", "form", "formal", "format", "formation",
  "former", "formerly", "formula", "forth", "fortune", "forty", "forum", "forward", "fossil",
  "foster", "fought", "found", "foundation", "founder", "fountain", "four", "fourth", "fraction",
  "fragile", "frame", "framework", "frank", "frankly", "fraud", "free", "freedom", "freely",
  "freeze", "french", "frequency", "frequent", "frequently", "fresh", "friday", "friend", "friendly",
  "friendship", "fright", "frighten", "frog", "from", "front", "frontier", "frost", "frozen",
  "fruit", "frustrate", "fuel", "fulfill", "full", "fully", "function", "fund", "fundamental",
  "funding", "funeral", "funny", "furniture", "further", "furthermore", "future",

  // === G ===
  "gain", "galaxy", "gallery", "game", "gang", "garage", "garbage", "garden", "garlic",
  "gather", "gave", "gaze", "gear", "gender", "gene", "general", "generally", "generate",
  "generation", "generous", "genetic", "genius", "gentle", "gentleman", "gently", "genuine", "gesture",
  "ghost", "giant", "gift", "gifted", "girl", "girlfriend", "give", "given", "glad",
  "glance", "glass", "global", "globe", "glory", "glove", "glow", "goal", "goat",
  "goes", "gold", "golden", "golf", "gone", "good", "goods", "gorgeous", "gospel",
  "gossip", "gotten", "govern", "government", "governor", "grab", "grace", "grade", "gradually",
  "graduate", "grain", "grand", "grandfather", "grandmother", "grant", "grape", "graph", "grasp",
  "grass", "grateful", "grave", "gravity", "gray", "great", "greater", "greatest", "greatly",
  "green", "greenhouse", "greet", "grew", "grief", "grill", "grin", "grind", "grip",
  "grocery", "gross", "ground", "group", "grow", "growing", "growth", "guarantee", "guard",
  "guess", "guest", "guidance", "guide", "guideline", "guilty", "guitar", "gulf", "gust",

  // === H ===
  "habit", "habitat", "hair", "half", "hall", "hallway", "halt", "hand", "handful",
  "handle", "handsome", "hang", "happen", "happy", "harbor", "hard", "hardly", "hardware",
  "harm", "harmful", "harmony", "harsh", "harvest", "hate", "have", "haven", "head",
  "headline", "headquarters", "heal", "health", "healthy", "heap", "hear", "heard", "hearing",
  "heart", "heat", "heaven", "heavily", "heavy", "heel", "height", "held", "helicopter",
  "hell", "hello", "help", "helpful", "hence", "hero", "herself", "hesitate", "hide",
  "high", "highlight", "highly", "highway", "hill", "himself", "hint", "hire", "historian",
  "historic", "historical", "history", "hold", "holder", "hole", "holiday", "hollow", "holy",
  "home", "homeland", "homeless", "homework", "honest", "honestly", "honey", "honor", "hook",
  "hope", "hopeful", "horizon", "horizontal", "hormone", "horn", "horrible", "horror", "horse",
  "hospital", "host", "hostage", "hotel", "hour", "house", "household", "housing", "however",
  "huge", "human", "humble", "humor", "hundred", "hunger", "hungry", "hunt", "hunter",
  "hunting", "hurt", "husband", "hypothesis",

  // === I ===
  "idea", "ideal", "identical", "identify", "identity", "ideology", "ignore", "illegal", "illness",
  "illustrate", "illustration", "image", "imagination", "imagine", "immediate", "immediately", "immigrant", "immigration",
  "impact", "implement", "implication", "imply", "import", "importance", "important", "impose", "impossible",
  "impress", "impression", "impressive", "improve", "improvement", "incentive", "inch", "incident", "include",
  "including", "income", "incorporate", "increase", "increased", "increasing", "increasingly", "incredible", "incredibly",
  "indeed", "independence", "independent", "index", "indicate", "indication", "indicator", "individual", "indoor",
  "industrial", "industry", "infant", "infection", "inflation", "influence", "inform", "information", "ingredient",
  "initial", "initially", "initiative", "injury", "inner", "innocent", "innovation", "input", "inquiry",
  "insect", "insert", "inside", "insight", "insist", "inspect", "inspection", "inspector", "inspiration",
  "inspire", "install", "installation", "instance", "instant", "instead", "institute", "institution", "instruction",
  "instructor", "instrument", "insurance", "intellectual", "intelligence", "intelligent", "intend", "intense", "intensity",
  "intention", "interaction", "interest", "interested", "interesting", "internal", "international", "internet", "interpret",
  "interpretation", "intervention", "interview", "into", "introduce", "introduction", "invasion", "invent", "invention",
  "invest", "investigate", "investigation", "investigator", "investment", "investor", "invite", "involve", "involved",
  "involvement", "iron", "island", "isolate", "isolation", "issue", "item", "itself",

  // === J ===
  "jacket", "jail", "january", "jazz", "jeans", "jelly", "jersey", "jewel", "jewelry",
  "jewish", "join", "joint", "joke", "journal", "journalist", "journey", "judge", "judgment",
  "juice", "july", "jump", "june", "jungle", "junior", "jury", "just", "justice",
  "justify",

  // === K ===
  "keen", "keep", "kept", "kernel", "keyboard", "kick", "kidney", "kill", "killer",
  "killing", "kind", "king", "kingdom", "kiss", "kitchen", "knee", "knew", "knife",
  "knock", "know", "knowing", "knowledge", "known",

  // === L ===
  "label", "labor", "laboratory", "lack", "ladder", "lady", "lake", "lamp", "land",
  "landing", "landlord", "landscape", "lane", "language", "laptop", "large", "largely", "larger",
  "largest", "laser", "last", "late", "lately", "later", "latest", "latin", "latter",
  "laugh", "laughter", "launch", "lawn", "lawsuit", "lawyer", "layer", "lead", "leader",
  "leadership", "leading", "leaf", "league", "lean", "learn", "learned", "learning", "least",
  "leather", "leave", "lecture", "left", "legacy", "legal", "legend", "legislation", "legitimate",
  "lemon", "lend", "length", "lens", "less", "lesson", "letter", "level", "liberal",
  "liberty", "library", "license", "lift", "light", "lighting", "like", "likely", "likewise",
  "limb", "limit", "limitation", "limited", "line", "link", "lion", "list", "listen",
  "listener", "literary", "literature", "little", "live", "lived", "lively", "liver", "living",
  "load", "loan", "lobby", "local", "locate", "location", "lock", "lodge", "logic",
  "logical", "lonely", "long", "longer", "look", "loop", "loose", "lord", "lose",
  "loss", "lost", "lots", "lottery", "loud", "love", "lovely", "lover", "lower",
  "luck", "lucky", "lunch", "lung", "luxury",

  // === M ===
  "machine", "machinery", "magazine", "magic", "magical", "magnetic", "magnificent", "mail", "main",
  "mainly", "mainstream", "maintain", "maintenance", "major", "majority", "make", "maker", "makeup",
  "male", "mall", "mama", "manage", "management", "manager", "manner", "manufacturer", "manufacturing",
  "many", "maple", "march", "margin", "marine", "mark", "market", "marketing", "marriage",
  "married", "marry", "mask", "mass", "massive", "master", "match", "mate", "material",
  "math", "mathematics", "matter", "maximum", "maybe", "mayor", "meal", "mean", "meaning",
  "meaningful", "means", "meanwhile", "measure", "measurement", "meat", "mechanism", "medal", "media",
  "medical", "medication", "medicine", "medium", "meet", "meeting", "member", "membership", "memo",
  "memorial", "memory", "mental", "mention", "mentor", "menu", "mercy", "mere", "merely",
  "merge", "merit", "mess", "message", "metal", "meter", "method", "middle", "midst",
  "might", "mighty", "mild", "mile", "military", "milk", "mill", "million", "mind",
  "mine", "mineral", "minimum", "minister", "ministry", "minor", "minority", "minute", "miracle",
  "mirror", "miss", "missile", "missing", "mission", "mistake", "mixed", "mixture", "mobile",
  "mode", "model", "moderate", "modern", "modest", "modify", "molecule", "moment", "momentum",
  "monday", "money", "monitor", "monkey", "month", "monthly", "mood", "moon", "moral",
  "more", "moreover", "morning", "mortgage", "most", "mostly", "mother", "motion", "motivate",
  "motivation", "motor", "mount", "mountain", "mouse", "mouth", "move", "movement", "movie",
  "much", "multiple", "murder", "muscle", "museum", "music", "musical", "musician", "must",
  "mutual", "myself", "mystery", "myth",

  // === N ===
  "nail", "naked", "name", "namely", "narrative", "narrow", "nation", "national", "native",
  "natural", "naturally", "nature", "navy", "near", "nearby", "nearly", "neat", "necessarily",
  "necessary", "neck", "need", "negative", "neglect", "negotiate", "negotiation", "neighbor", "neighborhood",
  "neither", "nerve", "nervous", "nest", "network", "neutral", "never", "nevertheless", "newborn",
  "newly", "news", "newspaper", "next", "nice", "night", "nightmare", "nine", "nobody",
  "nod", "noise", "nomination", "none", "nonetheless", "noon", "norm", "normal", "normally",
  "north", "northern", "nose", "notable", "note", "notebook", "nothing", "notice", "notion",
  "novel", "november", "nowhere", "nuclear", "number", "numerous", "nurse", "nursing", "nutrition",

  // === O ===
  "object", "objective", "obligation", "observation", "observe", "observer", "obtain", "obvious", "obviously",
  "occasion", "occasional", "occasionally", "occupation", "occupy", "occur", "ocean", "october", "odds",
  "offensive", "offer", "office", "officer", "official", "often", "okay", "olive", "olympic",
  "once", "ongoing", "onion", "online", "only", "onto", "open", "opening", "opera",
  "operate", "operating", "operation", "operator", "opinion", "opponent", "opportunity", "oppose", "opposed",
  "opposite", "opposition", "option", "orange", "orbit", "order", "ordinary", "organic", "organization",
  "organize", "orientation", "origin", "original", "originally", "other", "others", "otherwise", "ought",
  "ounce", "ourselves", "outcome", "outdoor", "outer", "outfit", "outline", "outlook", "output",
  "outside", "outstanding", "oven", "over", "overall", "overcome", "overlook", "overnight", "overseas",
  "overtime", "overview", "overwhelming", "owner", "ownership", "oxygen",

  // === P ===
  "pace", "pack", "package", "page", "paid", "pain", "painful", "paint", "painter",
  "painting", "pair", "palace", "pale", "palm", "panel", "panic", "paper", "parade",
  "paragraph", "parallel", "parent", "park", "parking", "parliament", "part", "partial", "participant",
  "participate", "participation", "particular", "particularly", "partly", "partner", "partnership", "party", "pass",
  "passage", "passenger", "passing", "passion", "past", "patch", "path", "patience", "patient",
  "pattern", "pause", "payment", "peace", "peaceful", "peak", "pear", "peasant", "peer",
  "penalty", "pencil", "penny", "pension", "people", "pepper", "percent", "percentage", "perception",
  "perfect", "perfectly", "perform", "performance", "perhaps", "period", "permanent", "permission", "permit",
  "persist", "person", "personal", "personality", "personally", "personnel", "perspective", "persuade", "phase",
  "phenomenon", "philosophy", "phone", "photo", "photograph", "photographer", "photography", "phrase", "physical",
  "physically", "physician", "piano", "pick", "picture", "piece", "pile", "pilot", "pine",
  "pink", "pioneer", "pipe", "pitch", "pizza", "place", "plain", "plan", "plane",
  "planet", "planning", "plant", "plastic", "plate", "platform", "play", "player", "playing",
  "plea", "pleasant", "please", "pleased", "pleasure", "pledge", "plenty", "plot", "plug",
  "plus", "pocket", "poem", "poet", "poetry", "point", "pole", "police", "policy",
  "political", "politically", "politician", "politics", "poll", "pollution", "pond", "pool", "poor",
  "popular", "popularity", "population", "pork", "port", "portion", "portrait", "pose", "position",
  "positive", "possess", "possession", "possibility", "possible", "possibly", "post", "poster", "potato",
  "potential", "potentially", "pottery", "pound", "pour", "poverty", "powder", "power", "powerful",
  "practical", "practice", "praise", "pray", "prayer", "precise", "precisely", "predict", "prediction",
  "prefer", "preference", "pregnancy", "pregnant", "premise", "premium", "preparation", "prepare", "prepared",
  "presence", "present", "presentation", "preserve", "president", "presidential", "press", "pressure", "presumably",
  "pretend", "pretty", "prevent", "previous", "previously", "price", "pride", "priest", "primarily",
  "primary", "prime", "principal", "principle", "print", "printer", "printing", "prior", "priority",
  "prison", "prisoner", "privacy", "private", "prize", "probably", "problem", "procedure", "proceed",
  "process", "produce", "producer", "product", "production", "productive", "profession", "professional", "professor",
  "profile", "profit", "program", "progress", "project", "prominent", "promise", "promote", "promotion",
  "prompt", "proof", "proper", "properly", "property", "proportion", "proposal", "propose", "proposed",
  "prosecutor", "prospect", "protect", "protection", "protein", "protest", "proud", "prove", "provide",
  "provider", "province", "provision", "psychological", "psychology", "public", "publication", "publicity", "publicly",
  "publish", "publisher", "pull", "pulse", "pump", "punch", "punishment", "pupil", "purchase",
  "pure", "purple", "purpose", "pursue", "push", "puzzle",

  // === Q ===
  "qualify", "quality", "quantity", "quarter", "queen", "query", "quest", "question", "quick",
  "quickly", "quiet", "quietly", "quit", "quite", "quote",

  // === R ===
  "rabbit", "race", "racial", "racing", "radar", "radical", "radio", "rage", "rail",
  "railroad", "railway", "rain", "rainbow", "raise", "rally", "ranch", "random", "range",
  "rank", "rapid", "rapidly", "rare", "rarely", "rate", "rather", "rating", "ratio",
  "reach", "react", "reaction", "read", "reader", "readily", "reading", "ready", "real",
  "realistic", "reality", "realize", "really", "realm", "rear", "reason", "reasonable", "reasonably",
  "rebel", "recall", "receipt", "receive", "receiver", "recent", "recently", "reception", "recipe",
  "recipient", "recognition", "recognize", "recommend", "recommendation", "record", "recording", "recover", "recovery",
  "recruit", "reduce", "reduction", "refer", "reference", "reflect", "reflection", "reform", "refugee",
  "refuse", "regard", "regarding", "regardless", "regime", "region", "regional", "register", "regular",
  "regularly", "regulate", "regulation", "reinforce", "reject", "relate", "related", "relation", "relationship",
  "relative", "relatively", "relax", "release", "relevant", "relief", "relieve", "religion", "religious",
  "rely", "remain", "remaining", "remains", "remark", "remarkable", "remedy", "remember", "remind",
  "remote", "removal", "remove", "render", "rent", "repair", "repeat", "replace", "replacement",
  "reply", "report", "reporter", "represent", "representation", "representative", "republic", "republican", "reputation",
  "request", "require", "requirement", "rescue", "research", "researcher", "reservation", "reserve", "residence",
  "resident", "residential", "resign", "resist", "resistance", "resolution", "resolve", "resort", "resource",
  "respect", "respond", "respondent", "response", "responsibility", "responsible", "rest", "restaurant", "restore",
  "restriction", "result", "retain", "retire", "retirement", "retreat", "return", "reveal", "revenue",
  "reverse", "review", "revolution", "revolutionary", "reward", "rhetoric", "rhythm", "rice", "rich",
  "ride", "rider", "ridge", "rifle", "right", "ring", "riot", "rise", "rising",
  "risk", "rival", "river", "road", "robot", "rock", "rocket", "role", "roll",
  "romance", "romantic", "roof", "room", "root", "rope", "rose", "rough", "roughly",
  "round", "route", "routine", "royal", "rubber", "ruin", "rule", "ruler", "ruling",
  "rumor", "rural", "rush", "russian",

  // === S ===
  "sacred", "sacrifice", "sadly", "safe", "safety", "sake", "salad", "salary", "sale",
  "salmon", "salt", "same", "sample", "sanction", "sand", "sandwich", "satellite", "satisfaction",
  "satisfy", "saturday", "sauce", "save", "saving", "scale", "scandal", "scared", "scenario",
  "scene", "schedule", "scheme", "scholar", "scholarship", "school", "science", "scientific", "scientist",
  "scope", "score", "scratch", "scream", "screen", "script", "seal", "search", "season",
  "seat", "second", "secondary", "secret", "secretary", "section", "sector", "secure", "security",
  "seed", "seek", "seem", "segment", "seize", "select", "selection", "self", "sell",
  "seller", "senate", "senator", "send", "senior", "sense", "sensitive", "sentence", "separate",
  "sequence", "series", "serious", "seriously", "servant", "serve", "server", "service", "session",
  "settle", "settlement", "seven", "several", "severe", "shade", "shadow", "shake", "shall",
  "shallow", "shame", "shape", "share", "shareholder", "sharp", "shatter", "shed", "sheep",
  "sheer", "sheet", "shelf", "shell", "shelter", "shift", "shine", "ship", "shipping",
  "shirt", "shock", "shoe", "shoot", "shooting", "shop", "shopping", "shore", "short",
  "shortly", "shot", "should", "shoulder", "shout", "show", "shower", "shut", "sibling",
  "sick", "side", "sigh", "sight", "sign", "signal", "signature", "significance", "significant",
  "significantly", "silence", "silent", "silk", "silver", "similar", "similarly", "simple", "simply",
  "since", "sing", "singer", "singing", "single", "sink", "sister", "site", "situation",
  "size", "skeptical", "sketch", "skill", "skilled", "skin", "skip", "skull", "slave",
  "sleep", "slice", "slide", "slight", "slightly", "slim", "slip", "slope", "slot",
  "slow", "slowly", "small", "smart", "smell", "smile", "smoke", "smoking", "smooth",
  "snap", "snow", "social", "society", "sock", "soft", "software", "soil", "solar",
  "sold", "soldier", "sole", "solely", "solid", "solution", "solve", "some", "somebody",
  "somehow", "someone", "something", "sometimes", "somewhat", "somewhere", "song", "soon", "sophisticated",
  "sorry", "sort", "soul", "sound", "soup", "source", "south", "southern", "space",
  "span", "spare", "spark", "speak", "speaker", "speaking", "special", "specialist", "species",
  "specific", "specifically", "specify", "spectacular", "spectrum", "speech", "speed", "spell", "spelling",
  "spend", "spending", "sphere", "spill", "spin", "spirit", "spiritual", "spite", "split",
  "spokesman", "sponsor", "sport", "spot", "spouse", "spread", "spring", "squad", "square",
  "squeeze", "stability", "stable", "stack", "staff", "stage", "stair", "stake", "stamp",
  "stand", "standard", "standing", "star", "stare", "start", "state", "statement", "station",
  "statistical", "statistics", "status", "stay", "steady", "steal", "steam", "steel", "steep",
  "steer", "stem", "step", "stick", "stiff", "still", "stimulate", "stimulus", "stir",
  "stock", "stomach", "stone", "stop", "storage", "store", "storm", "story", "straight",
  "strain", "strand", "strange", "stranger", "strategic", "strategy", "straw", "stream", "street",
  "strength", "strengthen", "stress", "stretch", "strict", "strictly", "strike", "string", "strip",
  "stroke", "strong", "strongly", "structural", "structure", "struggle", "student", "studio", "study",
  "stuff", "stumble", "stupid", "style", "subject", "submit", "subsequent", "substance", "substantial",
  "subtle", "succeed", "success", "successful", "successfully", "such", "sudden", "suddenly", "suffer",
  "sufficient", "sugar", "suggest", "suggestion", "suicide", "suit", "suite", "summer", "summit",
  "sunday", "super", "superior", "supplement", "supply", "support", "supporter", "suppose", "supposed",
  "supreme", "sure", "surely", "surface", "surgeon", "surgery", "surplus", "surprise", "surprised",
  "surprising", "surprisingly", "surround", "surrounding", "survey", "survival", "survive", "survivor", "suspect",
  "suspend", "sustain", "swallow", "swear", "sweat", "sweep", "sweet", "swim", "swimming",
  "swing", "switch", "symbol", "sympathy", "symptom", "syndrome", "system",

  // === T ===
  "table", "tablespoon", "tactic", "tail", "take", "taken", "tale", "talent", "talented",
  "talk", "talking", "tall", "tank", "tape", "target", "task", "taste", "taught",
  "taxation", "taxpayer", "teach", "teacher", "teaching", "team", "tear", "teaspoon", "technical",
  "technique", "technology", "teenager", "telephone", "telescope", "television", "tell", "temperature", "temple",
  "temporarily", "temporary", "tend", "tendency", "tender", "tennis", "tension", "tent", "term",
  "terms", "terrible", "territory", "terror", "terrorism", "terrorist", "test", "testing", "text",
  "textbook", "texture", "than", "thank", "thanks", "thanksgiving", "that", "theater", "their",
  "them", "theme", "themselves", "then", "theoretical", "theory", "therapy", "there", "thereby",
  "therefore", "these", "thick", "thin", "thing", "think", "thinking", "third", "thirty",
  "this", "thorough", "thoroughly", "those", "though", "thought", "thousand", "thread", "threat",
  "threaten", "three", "threshold", "thrive", "throat", "through", "throughout", "throw", "thrown",
  "thrust", "thumb", "thursday", "thus", "ticket", "tide", "tight", "tightly", "tile",
  "till", "time", "timeline", "tiny", "tire", "tired", "tissue", "title", "tobacco",
  "today", "together", "toilet", "tolerance", "toll", "tomato", "tomorrow", "tone", "tongue",
  "tonight", "tool", "tooth", "topic", "torn", "total", "totally", "touch", "tough",
  "tour", "tourism", "tourist", "tournament", "toward", "towards", "tower", "town", "toxic",
  "trace", "track", "trade", "tradition", "traditional", "traffic", "tragedy", "trail", "train",
  "trainer", "training", "trait", "transfer", "transform", "transformation", "transition", "translate", "translation",
  "transmission", "transmit", "transparent", "transport", "transportation", "trap", "trash", "travel", "traveler",
  "treasure", "treat", "treatment", "treaty", "tree", "tremendous", "trend", "trial", "triangle",
  "tribe", "tribute", "trick", "trigger", "trim", "trip", "triumph", "troop", "tropical",
  "trouble", "troubled", "truck", "true", "truly", "trunk", "trust", "truth", "tuesday",
  "tumor", "tune", "tunnel", "turkey", "turn", "twelve", "twenty", "twice", "twin",
  "twist", "type", "typical", "typically",

  // === U ===
  "ugly", "ultimate", "ultimately", "unable", "uncle", "undergo", "underlying", "understand", "understanding",
  "undertake", "unemployment", "unexpected", "unfair", "unfortunately", "unhappy", "uniform", "union", "unique",
  "unit", "united", "unity", "universal", "universe", "university", "unknown", "unless", "unlike",
  "unlikely", "unnecessary", "until", "unusual", "update", "upon", "upper", "upset", "urban",
  "urge", "urgent", "usage", "used", "useful", "user", "usual", "usually", "utility",

  // === V ===
  "vacation", "vaccine", "valid", "valley", "valuable", "value", "vanilla", "variable", "variation",
  "variety", "various", "vary", "vast", "vegetable", "vehicle", "vendor", "venture", "venue",
  "verbal", "verse", "version", "versus", "vertical", "very", "vessel", "veteran", "viable",
  "vice", "victim", "victory", "video", "view", "viewer", "village", "violate", "violation",
  "violence", "violent", "virtual", "virtually", "virtue", "virus", "visible", "vision", "visit",
  "visitor", "visual", "vital", "vivid", "vocabulary", "voice", "volume", "voluntary", "volunteer",
  "vote", "voter", "voting", "vulnerable",

  // === W ===
  "wage", "wait", "wake", "walk", "walking", "wall", "wander", "want", "warfare",
  "warm", "warmth", "warn", "warning", "warrant", "warrior", "wash", "waste", "watch",
  "water", "wave", "weak", "weakness", "wealth", "wealthy", "weapon", "wear", "weather",
  "weave", "website", "wedding", "wednesday", "week", "weekend", "weekly", "weigh", "weight",
  "weird", "welcome", "welfare", "well", "west", "western", "whale", "what", "whatever",
  "wheat", "wheel", "wheelchair", "when", "whenever", "where", "whereas", "wherever", "whether",
  "which", "while", "whisper", "white", "whole", "whom", "whose", "wide", "widely",
  "widespread", "wife", "wild", "wildlife", "will", "willing", "wind", "window", "wine",
  "wing", "winner", "winter", "wipe", "wire", "wisdom", "wise", "wish", "with",
  "withdraw", "withdrawal", "within", "without", "witness", "wolf", "woman", "women", "wonder",
  "wonderful", "wood", "wooden", "wool", "word", "work", "worker", "working", "workout",
  "workplace", "workshop", "world", "worried", "worry", "worse", "worship", "worst", "worth",
  "worthy", "would", "wound", "wrap", "wrist", "write", "writer", "writing", "written",
  "wrong",

  // === X ===
  "xerox",

  // === Y ===
  "yard", "yeah", "year", "yell", "yellow", "yesterday", "yield", "yoga", "young",
  "youngster", "your", "yours", "yourself", "youth",

  // === Z ===
  "zero", "zone", "zoom",
]);
